version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      PORT: 8000
      DATABASE_URL: "postgres://postgres:password@db/postgres"
      ROCKET_ADDRESS: "0.0.0.0"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
