version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      PORT: 8000
      DATABASE_URL: "postgres://postgres:password@db/postgres"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  frontend:
    build:
      context: ./frontend
      args:
        BOOKS_HOST: http://localhost
        BOOKS_PORT: 8000
    ports:
      - "5000:5000"
    restart: always
