name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      APP_NAME: cryptic-anchorage-09442
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t book-db backend/ 
      - run: docker tag book-db registry.heroku.com/$APP_NAME/web
      - run: heroku container:login
      - run: docker push registry.heroku.com/$APP_NAME/webdocker
      - run: heroku container:release -a $APP_NAME web
