name: Frontend validation
on: pull_request
jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm run lint
      - run: npm run test
