name: Frontend validation
on:
  pull_request:
    paths:
      - frontend
jobs:
  validate-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - uses: Dunklas/pr-quote-action@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  